# Generated by Django 4.2.26 on 2025-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Province Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Population')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Area (km²)')),
                ('geojson_data', models.TextField(blank=True, help_text='GeoJSON geometry for the province', verbose_name='GeoJSON Data')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
    ]
