# Generated by Django 4.2.26 on 2025-11-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste SVG code here', verbose_name='Icon SVG'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Tailwind text color class (e.g., text-blue-800)', max_length=50, verbose_name='Color Class'),
        ),
    ]
