# Generated by Django 4.2.26 on 2025-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statistic_icon_svg_alter_statistic_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('action_text', models.CharField(blank=True, max_length=50, verbose_name='Action Button Text')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Is Urgent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Alert',
                'verbose_name_plural': 'AI Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='icon_svg',
        ),
        migrations.AddField(
            model_name='statistic',
            name='color_class',
            field=models.CharField(default='bg-blue-600', help_text='Tailwind background class (e.g., bg-red-600)', max_length=50, verbose_name='Background Color'),
        ),
    ]
