# Generated by Django 4.2.26 on 2025-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('line_current', 'Line Chart (Current Year)'), ('line_previous', 'Line Chart (Previous Year)'), ('bar_monthly', 'Bar Chart (Monthly Status)')], max_length=50, verbose_name='Chart Type')),
                ('month', models.IntegerField(verbose_name='Month (1-12)')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Label (e.g., Month Name)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color (Hex or Class)')),
            ],
            options={
                'verbose_name': 'Chart Data Point',
                'verbose_name_plural': 'Chart Data Points',
                'ordering': ['chart_type', 'month'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pillar Name')),
                ('value', models.IntegerField(verbose_name='Value (%)')),
                ('color', models.CharField(default='#3B82F6', max_length=50, verbose_name='Color (Hex)')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Development Pillar',
                'verbose_name_plural': 'Development Pillars',
                'ordering': ['order'],
            },
        ),
    ]
