# Generated by Django 4.2.26 on 2025-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_navigationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='المشاريع الذكية', max_length=200, verbose_name='Site Title')),
                ('ai_alerts_title', models.CharField(default='التنبيهات الذكية - AI Alerts', max_length=200, verbose_name='AI Alerts Title')),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
