# Generated by Django 4.2.26 on 2025-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dashboardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, help_text='Path to video file (e.g., /static/core/video.mp4)', max_length=200, null=True, verbose_name='Project Video'),
        ),
    ]
